### ISSUE TITLE
Clicking on the Worker name does nothing

### ISSUE THREAD

**Issue by hassek** [aclowes/yawn#4]
![image](https://cloud.githubusercontent.com/assets/778410/22340661/8c661814-e3c4-11e6-9f5f-f53b79344678.png)

Then I click and -->

![image](https://cloud.githubusercontent.com/assets/778410/22340668/950584d2-e3c4-11e6-8419-5ea458ce02e7.png)

**Comment by aclowes** [comment]
Fixed
