### ISSUE TITLE
Can't Terminate workers on the UI

### ISSUE THREAD

**Issue by hassek** [aclowes/yawn#5]
When I go to the Workers Tab, I can't click on the Terminate button, no mattering the status of the worker. 

![worker_tab](https://cloud.githubusercontent.com/assets/778410/22340847/315826c8-e3c5-11e6-8e64-8e1b11e4329a.gif)

**Comment by aclowes** [comment]
Thanks. I've removed that button, since remotely terminating a worker doesn't make that much sense... it's not like one can remotely start a worker.
